#spring.application.name=03_AccountService
#spring.datasource.url=jdbc:oracle:thin:@10.10.196.37:1521:testdev1
#spring.datasource.username=SOLARGC
#spring.datasource.password=SOLARGC
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#logging.file.name=logs/account.log
#server.port=8081
spring:
    application:
      name: "account-service"
    datasource:
      url: jdbc:oracle:thin:@10.10.196.37:1521:testdev1
      driver-class-name: oracle.jdbc.OracleDriver
      username: SOLARGC
      password: SOLARGC

server: 
    port: 8081
logging:
    file:
      name: logs/account.log
build:
    version: "1.0"
account:
    message: "Welcome to MSEDCL bank customer created REST API--TRANSACTION PROD "
    contactDetails:
      name: "shraddha"
      email: "shraddha@msedcl.in"
    onCallSupport:
      -1234567890
      -9876543210
